--------------------------------------------------------
--  파일이 생성됨 - 월요일-9월-01-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LOG
--------------------------------------------------------

  CREATE TABLE "SENSOR"."LOG" 
   (	"LOG_ID" NUMBER, 
	"HUMAN_DETECT" NUMBER(1,0), 
	"OBJ_DETECT" NUMBER(1,0), 
	"ACTION" VARCHAR2(10 BYTE), 
	"LOG_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SENSOR.LOG
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007525
--------------------------------------------------------

  CREATE UNIQUE INDEX "SENSOR"."SYS_C007525" ON "SENSOR"."LOG" ("LOG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger SENSOR_LOG_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SENSOR"."SENSOR_LOG_TRG" 
BEFORE INSERT ON SENSOR.LOG
FOR EACH ROW
BEGIN
    IF :NEW.LOG_ID IS NULL THEN
        SELECT SENSOR_LOG_SEQ.NEXTVAL INTO :NEW.LOG_ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER "SENSOR"."SENSOR_LOG_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table LOG
--------------------------------------------------------

  ALTER TABLE "SENSOR"."LOG" ADD PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SENSOR"."LOG" MODIFY ("ACTION" NOT NULL ENABLE);
  ALTER TABLE "SENSOR"."LOG" MODIFY ("OBJ_DETECT" NOT NULL ENABLE);
  ALTER TABLE "SENSOR"."LOG" MODIFY ("HUMAN_DETECT" NOT NULL ENABLE);
